### ISSUE TITLE
run for parameter agent: Cannot assign configuration entry 'agent' with value

### ISSUE THREAD

**Issue by jagdeep786** [BroadleafCommerce/DemoSite#12]
[INFO] --- spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) @ boot-community-demo-site ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.363 s
[INFO] Finished at: 2017-08-01T11:25:37+05:30
[INFO] Final Memory: 32M/362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) on project boot-community-demo-site: Unable to parse configuration of mojo org.springframework.boot:spring-boot-maven-plugin:1.5.4.RELEASE:run for parameter agent: Cannot assign configura
tion entry 'agent' with value 'E:\DemoSite\site\target/agents/spring-instrument.jar' of type java.lang.String to property of type java.io.File[] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException

**Comment by jagdeep786** [comment]
At least maven 3.5.x is required. 
I updated the maven from 3.3.3 to 3.5.x. After that clean the build and install again.

**Comment by phillipuniverse** [comment]
Sorry about that, our getting started docs reference a minimum version of Maven 3.3.3. In actuality, the minimum version of Maven is 3.3.9. I have updated the docs to reflect this.
