### ISSUE TITLE
mvn spring-boot:run is failing

### ISSUE THREAD

**Issue by lenical** [BroadleafCommerce/DemoSite#21]
On the root level I have done
`mvn clean install`
with Build Success

then go to admin (, same for site or api )
and I have got:
`C:\DEV\DemoSite\DemoSite-5.2.0-GA\admin>mvn spring-boot:run
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=false
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Community Demo Admin 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) @ boot-commu
nity-demo-admin >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ boot-commu
nity-demo-admin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 10 resources
[INFO]
[INFO] --- jrebel-maven-plugin:1.1.7:generate (generate-rebel-xml) @ boot-commun
ity-demo-admin ---
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ boot-community-
demo-admin ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-dependency-plugin:2.10:copy (copy-agent) @ boot-community-demo-
admin ---
[INFO] Configured Artifact: org.springframework:spring-instrument:4.3.9.RELEASE:
jar
[INFO] org.springframework:spring-instrument:4.3.9.RELEASE:jar already exists in
 C:\DEV\DemoSite\DemoSite-5.2.0-GA\admin\target\agents
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ bo
ot-community-demo-admin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\DEV\DemoSite\DemoSite-5.2.0-GA\adm
in\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ boot-co
mmunity-demo-admin ---
[INFO] No sources to compile
[INFO]
[INFO] <<< spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) @ boot-commu
nity-demo-admin <<<
[INFO]
[INFO] --- spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) @ boot-commu
nity-demo-admin ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.178s
[INFO] Finished at: Fri Sep 01 13:07:31 AEST 2017
[INFO] Final Memory: 23M/333M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin
:1.5.4.RELEASE:run (default-cli) on project boot-community-demo-admin: Unable to
 parse configuration of mojo org.springframework.boot:spring-boot-maven-plugin:1
.5.4.RELEASE:run for parameter agent: Cannot assign configuration entry 'agent'
with value 'C:\DEV\DemoSite\DemoSite-5.2.0-GA\admin\target/agents/spring-instrum
ent.jar' of type java.lang.String to property of type java.io.File[] -> [Help 1]

[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigur
ationException`

Thanks for your help

**Comment by phillipuniverse** [comment]
What version of Maven are you using? It appears that you are using 3.2, you should be using at least Maven 3.3.9 (the latest version is 3.5.0).

**Comment by phillipuniverse** [comment]
Closing, assuming that the issue was related to Maven version.
