### ISSUE TITLE
Disable https redirect

### ISSUE THREAD

**Issue by AR1ES** [BroadleafCommerce/DemoSite#26]
BroadleafCommerce version 5.2.2.1-GA.
How to disable redirect from port 8080 to 8443?
I can't use default http protocol. I always get redirected to 8443 port (or 8444 for admin site).
What is the reason?

**Comment by linuxidefix** [comment]
Go to Site/AdminSecurityConfig the following lines required all site to be in https.
```
.requiresChannel()
                .antMatchers("/**")
                .requiresSecure()
                .and()
```
and you may have a port Mapper too that defines port redirection.
By default, Spring security adds a portMapper that configures automatically 2 redirections 80->443, 8080->8443. So this is the last redirection rule that defines the redirection.
(This is why there is no portMapper in the front and one in the admin )
```
             .portMapper().
                http(httpPort).
                mapsTo(httpsPort).
                and()
```

If you remove the 1st part, https redirection will be disabled as the whole site will not have to be secured.

Maybe be in your case you could to create your own PortMapper with no redirection rule.

**Comment by AR1ES** [comment]
Thanks! It works!
