### ISSUE TITLE
Homepage cannot be displayed because of missing template

### ISSUE THREAD

**Issue by linuxidefix** [BroadleafCommerce/DemoSite#3]
http://localhost:8080 displays the flollowing error
(other pages are ok)
> Error resolving template "layout/homepage"

- BroadleafCategoryController redirects to **layout/homepage** instead of **layout/home**
- The problem comes from the sql data:
In _/config/bc/sql/demo/load_catalog_data.sql_, the **DISPLAY_TEMPLATE** of the root category has been set to **layout/homepage** instead of **layout/home**

**Comment by cja769** [comment]
@linuxidefix Thanks for finding that. The template name was updated to match the sql.
