### ISSUE TITLE
catalog/partials/productPagingOptions links are wrong when demo is deployed to Tomcat.

### ISSUE THREAD

**Issue by rcampion** [BroadleafCommerce/DemoSite#55]
When I deploy the demo as /shop to Tomcat, the product paging options point to http://127.0.0.1:9090/shop/products?page=2,  not the context of the application.

**Comment by cja769** [comment]
I'm not sure I understand the issue. I changed the context path via Spring Boot to `/shop` and didn't see any issues. There shouldn't be any difference from doing that and deploying to Tomcat

**Comment by rcampion** [comment]
My full URL is https://www.zdslogic.com/shop/products

I use Nginx to redirect and hide the port.

paging points to http://127.0.0.1:9090/shop/products

**Comment by cja769** [comment]
This is generated via `PaginationPageLinkProcessor` using `HttpServletRequest#getRequestURL`. This should give the correct URL therefore it seems that the application is seeing the URL as it's returning it. The processor isn't particularly necessary and can be ignored for vanilla Thymeleaf. For example replace

```
        <ul class="pagination pagination-primary">
            <li class="inactive pagination-arrow">
                <a th:if="${result.page > 1}" blc:paginationpagelink="${result.page - 1}"><span>&lt;</span></a>
                <a th:unless="${result.page > 1}" class="disabled" href="javascript:void(0);"><span>&lt;</span></a>
            </li>
            <li th:each="num : ${#numbers.sequence(1, result.totalPages)}" th:class="${result.page == num}? 'active' : 'inactive'">
                <a blc:paginationpagelink="${num}"><span th:utext="${num}"></span></a>
            </li>
            <li class="inactive pagination-arrow">
                <a th:if="${result.page < result.totalPages}" blc:paginationpagelink="${result.page + 1}"><span>&gt;</span></a>
                <a th:unless="${result.page < result.totalPages}" class="disabled" href="javascript:void(0);"><span>&gt;</span></a>
            </li>
```
with
```
        <ul class="pagination pagination-primary">
            <li class="inactive pagination-arrow">
                <a th:if="${result.page > 1}" th:href="@{''(page=${result.page - 1})}"><span>&lt;</span></a>
                <a th:unless="${result.page > 1}" class="disabled" href="javascript:void(0);"><span>&lt;</span></a>
            </li>
            <li th:each="num : ${#numbers.sequence(1, result.totalPages)}" th:class="${result.page == num}? 'active' : 'inactive'">
                <a th:href="@{''(page=${num})}"><span th:utext="${num}"></span></a>
            </li>
            <li class="inactive pagination-arrow">
                <a th:if="${result.page < result.totalPages}" th:href="@{''(page=${result.page + 1})}"><span>&gt;</span></a>
                <a th:unless="${result.page < result.totalPages}" class="disabled" href="javascript:void(0);"><span>&gt;</span></a>
            </li>
        </ul>
```` 

if this doesn't work then there's nothing on the application side that can be done without directly referencing the domain name since it seems that the application has no knowledge of that domain name.

**Comment by phillipuniverse** [comment]
@rcampion it is likely that you need to do 2 things:

1. Have Nginx send `X-Forwarded-*` headers when proxying to Tomcat
2. Configure Tomcat's [RemoteIPValve](https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html) to use those `X-Forwarded-*` headers

Example nginx configuration:

```java
location / {
    proxy_pass http://tomcat;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by phillipuniverse** [comment]
There is a lot of additional information on this issue at #49

**Comment by rcampion** [comment]
@phillipuniverse 

Thank you very much.  
I only had to modify the nginx configuration.  
I didn't have to change Tomcat.

Regards
