### ISSUE TITLE
How to avoid - Too many connections for role "xxx"

### ISSUE THREAD

**Issue by diogo10** [BroadleafCommerce/DemoSite#59]
Hi guys, thanks for this great repo!

I am trying to deploy it on Heroku for my wife project. Got a Postgres database but the Hibernate seams to open to many connections at front. I tried to include c3p0 but it does not work at all. 

I am doing it:

`
blPU.hibernate.c3p0.min_size=5
blPU.hibernate.c3p0.max_size=15
blPU.hibernate.connection.provider_class=org.hibernate.connection.C3P0ConnectionProvider
`
On all connections, but it does not work. Did somebody tries that? How would be a good approach?

**Comment by cja769** [comment]
I would refer to the [Spring Boot 2.0.4.RELEASE docs](https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/html/boot-features-sql.html#boot-features-connect-to-production-database) that talk about database connections. It depends on your configuration but with the default DemoSite configuration Hibernate will use Tomcat for the connection pool so you'll have to configure it using those properties. If you could post additional logs such as a full stacktrace it would be helpful. Additionally please specify which version of Broadleaf you're using. As the docs mentioned, if you're using Spring Boot 2, then Spring will automatically hook up everything for using HikariCP if the dependency is available so I would suggest using it over c3p0.
