### ISSUE TITLE
[BUG] - Product's parent category is not saved in admin

### ISSUE THREAD

**Issue by linuxidefix** [BroadleafCommerce/DemoSite#7]
Scenario: 
------------
The scenario is a basic one: I want to create a test product in the admin and see it on the front under 'sauces' category.

Results:
-----------
Product is created and searcheable* but is not displayed on the page category. ( #5 i did a dirty fix to make it work )  
But it appears that the parent's category property is not saved in the admin. So the product is not linked to the desired category and that could explain the previous behavior.

Steps:
------------
- Create a test product with basic information and attach it to "sauces" category
- Save
- Refresh page

Log:
------
No errors log

Version:
----------
Community Starter (BLC 5.2, hsqldb)

![product-a-create_a_product](https://cloud.githubusercontent.com/assets/836182/26221766/e76298b8-3c17-11e7-9069-f38bdf9ae815.png)
![product-b-saved](https://cloud.githubusercontent.com/assets/836182/26221765/e7601b88-3c17-11e7-8a3e-aa617cc716d0.png)
![product-c-refreshed](https://cloud.githubusercontent.com/assets/836182/26221767/e763058c-3c17-11e7-8328-59ae6d071009.png)

This issue could be also linked to this closed issue: 
https://github.com/BroadleafCommerce/BroadleafCommerce/issues/1586

**Comment by phillipuniverse** [comment]
Fixed in the latest 5.2.0-SNAPSHOT
